name: pet_adoption_app
description: app for pet adoption
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  glassmorphism_ui: ^0.3.0
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6
  hive_flutter: ^1.1.0
  line_icons: ^2.0.1
  path_provider: ^2.0.11
  shared_preferences: ^2.0.16
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/database/pets.json
